### ISSUE TITLE
feat: add responsive classes for different device type

### ISSUE THREAD

**Issue by matt-d-webb** [jimmybutton/react-tailwind-table#2]
It would be great if this project also included the tailwind [responsive classes](https://tailwindcss.com/docs/breakpoints) `sm: md: lg:`. etc. So that the table is usable across device types.

I am currently working to add these myself to [my project](https://github.com/chess-centre/platform), happy to raise a PR / discussion topic with some suggestions.

WIP:
![image](https://user-images.githubusercontent.com/36933715/132519673-cc842b66-5e45-41ae-aa10-f86d862ebb01.png)
[Project PR](https://github.com/chess-centre/platform/pull/331)

Key considerations:
- Overflow handling for x-scroll
- Global filter handling (good ux to avoid overwhelming input / dropdowns)

**Comment by jimmybutton** [comment]
Hi @matt-d-webb , many thanks for your comment. however, i am not sure what exactly you mean. imo the table works already well on mobile. you'll get the horizontal scrollbar, simplified pagination controls and also no horizontal margin.
![image](https://user-images.githubusercontent.com/45269373/134770381-ce678f37-f8a8-446a-a648-a64fea0c3f42.png)
regarding the filters, the objective of this project was to demonstrate how to integration custom filters with React Table. I think i'd prefer to keep it that way and not provide an opinionated solution.
